// import Hello from "./components/hello";

export const metadata = {
  title: "Home | Next.js",
  description: "Generated by create next app",
}

export default function Home() {
  return (
    <>
      <h1> Welcome to Next.js! </h1>
      {/* <Hello /> */}
    </>
  );
}
